apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - secret.yaml

#configMapGenerator:
#  - name: my-app-config
#    literals:
#      - APP_ENV=production
#      - APP_LOG_LEVEL=info
#
